title: Pattern Library
description: A collection of patterns to help you build up a style guide for your site

baseurl: /
url:     /styleguide

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']
gems:        []
timezone:    Europe/London
markdown:    kramdown
permalink:   pretty
highlighter: pygments

collections:
- patterns

sass:
    sass_dir: ./style/_sass
